global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'gitlab'
    metrics_path: '/-/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:80']
  - job_name: 'my_app'
    static_configs:
        - targets: [ 'localhost:3000' ]
